apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: linnex/task-worker:latest
          ports:
          - containerPort: 9091
          env:
          - name: NATS_URL
            value: "nats://nats:4222"
          - name: MINIO_ENDPOINT
            value: "minio:9000"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  ports:
  - port: 9091
    targetPort: 9091
  selector:
    app: worker
  clusterIP: None
